import Header from "@/components/Header";
import "../../app/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Forums",
  description: "Generated by create next app",
};

export default function layout({ children }: { children: React.ReactNode }) {
  return (
    <>
      <main>{children}</main>
    </>
  );
}
